name: Code Quality - Static code - cppcheck

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  cppcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt - y install cppcheck
    - name: Run cppcheck
      run: cppcheck M1_Project-march-main 3_implementation
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
